name: plc-project

on: [push, pull_request]

env:

jobs:
  check_program:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    needs: check_coding_style
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Launch "make"
        run: make
        timeout-minutes: 2
      - name: Launch "make clean"
        run: make clean
      - name: Launch "make tests_run"
        run: make tests_run
        timeout-minutes: 2
